server:
  port: 8080

spring:
  application:
    name: asset-manager

  profiles:
    active: dev

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=AssetManager;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html